# This file cannot sit in the project file, because VS has issues with the project type.
# base image
FROM node:10.15.0
 
# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
 
# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY . .

#point the server at our api container port. Contained in the docker-compose.yml
RUN rm .env
RUN echo "VUE_APP_API_PORT=30390" > .env

RUN npm install
RUN npm install -g @vue/cli

# start app
CMD ["npm", "run", "serve"]
#CMD tail -f /dev/null